"""empty message

Revision ID: 21eab76138bb
Revises: 6d0bd3f38108
Create Date: 2022-11-08 09:41:33.802564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eab76138bb'
down_revision = '6d0bd3f38108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_pulled', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_pulled')
    # ### end Alembic commands ###
