"""empty message

Revision ID: 419ccebfced6
Revises: 4e49a3232289
Create Date: 2022-12-01 18:55:38.572071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419ccebfced6'
down_revision = '4e49a3232289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_album_to_song_album_id', table_name='album_to_song')
    op.drop_index('ix_album_to_song_song_id', table_name='album_to_song')
    op.drop_table('album_to_song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_to_song',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('song_id', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_album_to_song_song_id', 'album_to_song', ['song_id'], unique=False)
    op.create_index('ix_album_to_song_album_id', 'album_to_song', ['album_id'], unique=False)
    # ### end Alembic commands ###
