"""empty message

Revision ID: 6d0bd3f38108
Revises: 
Create Date: 2022-11-07 15:10:24.332798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0bd3f38108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.String(length=64), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_to_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_to_song_artist_id'), 'artist_to_song', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_to_song_song_id'), 'artist_to_song', ['song_id'], unique=False)
    op.create_table('user_to_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_to_song_song_id'), 'user_to_song', ['song_id'], unique=False)
    op.create_index(op.f('ix_user_to_song_user_id'), 'user_to_song', ['user_id'], unique=False)
    op.create_table('userto_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userto_artist_artist_id'), 'userto_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_userto_artist_user_id'), 'userto_artist', ['user_id'], unique=False)
    op.create_table('album_to_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_to_song_album_id'), 'album_to_song', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_to_song_song_id'), 'album_to_song', ['song_id'], unique=False)
    op.create_table('user_to_album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_to_album_album_id'), 'user_to_album', ['album_id'], unique=False)
    op.create_index(op.f('ix_user_to_album_user_id'), 'user_to_album', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_to_album_user_id'), table_name='user_to_album')
    op.drop_index(op.f('ix_user_to_album_album_id'), table_name='user_to_album')
    op.drop_table('user_to_album')
    op.drop_index(op.f('ix_album_to_song_song_id'), table_name='album_to_song')
    op.drop_index(op.f('ix_album_to_song_album_id'), table_name='album_to_song')
    op.drop_table('album_to_song')
    op.drop_index(op.f('ix_userto_artist_user_id'), table_name='userto_artist')
    op.drop_index(op.f('ix_userto_artist_artist_id'), table_name='userto_artist')
    op.drop_table('userto_artist')
    op.drop_index(op.f('ix_user_to_song_user_id'), table_name='user_to_song')
    op.drop_index(op.f('ix_user_to_song_song_id'), table_name='user_to_song')
    op.drop_table('user_to_song')
    op.drop_index(op.f('ix_artist_to_song_song_id'), table_name='artist_to_song')
    op.drop_index(op.f('ix_artist_to_song_artist_id'), table_name='artist_to_song')
    op.drop_table('artist_to_song')
    op.drop_table('album')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('artist')
    # ### end Alembic commands ###
