"""empty message

Revision ID: b0d96b84a3eb
Revises: 071546e8a201
Create Date: 2022-11-29 15:08:02.817042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d96b84a3eb'
down_revision = '071546e8a201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_to_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(length=64), nullable=True),
    sa.Column('song_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_to_song_album_id'), 'album_to_song', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_to_song_song_id'), 'album_to_song', ['song_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_to_song_song_id'), table_name='album_to_song')
    op.drop_index(op.f('ix_album_to_song_album_id'), table_name='album_to_song')
    op.drop_table('album_to_song')
    # ### end Alembic commands ###
